services:
    database:
        image: "postgres:17.5"
        ports:
            - "8081:5432"
        volumes:
            - "spring-boot-postgresql:/var/lib/postgresql/data"
        environment:
            - "POSTGRES_PASSWORD=password"

volumes:
    spring-boot-postgresql:
        # Nothing here indicates that the default config should be used.
