package farbfetzen.spring_boot_postgresql;

import java.time.Instant;
import java.util.UUID;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.annotation.ReadOnlyProperty;
import org.springframework.data.annotation.Version;
import org.springframework.data.relational.core.mapping.Table;

@Table("users")
@Data
@AllArgsConstructor(onConstructor_ = {@PersistenceCreator})
@NoArgsConstructor(force = true)
public class User {

    // This is final because the id is generated by the database.
    @Id
    private final UUID id;

    @Version
    private int version;

    private String email;

    private String name;

    // This is final and ReadOnlyProperty because the date gets set by the database
    // and should never be changed by the app.
    @ReadOnlyProperty
    private final Instant createdAt;
}
